export type CaseLocale = "zh" | "en";

export type CustomerCase = {
  id: string;
  category: "product" | "avatar" | "commerce" | "business";
  title: Record<CaseLocale, string>;
  description: Record<CaseLocale, string>;
  thumbnailUrl: string;
  videoUrl: string;
  taskId: string;
  duration: string;
  language: CaseLocale | "multi";
  featured?: boolean;
};

export const customerCases: CustomerCase[] = [
  {
    id: "ai-avatar-production-demo",
    category: "avatar",
    title: {
      zh: "真实 AI 数字人口播演示",
      en: "Real AI Talking Avatar Demo",
    },
    description: {
      zh: "生产环境完整链路生成：输入文案、自动配音、MuseTalk 数字人口播和 MP4 下载。",
      en: "Generated through the production flow: script input, synthesized voice, MuseTalk avatar video, and MP4 delivery.",
    },
    thumbnailUrl: "/avatars/ai_female_01.png",
    videoUrl: "https://povfvhdnrpytxbbyndit.supabase.co/storage/v1/object/public/videos/avatar-results/4fd1dcc5-aab9-43b9-bb40-0b8d387e23fd/4a82173de1704d3897fda054fb100151.mp4?",
    taskId: "4fd1dcc5-aab9-43b9-bb40-0b8d387e23fd",
    duration: "14.112s",
    language: "zh",
    featured: true,
  },
  {
    id: "static-avatar-production-demo",
    category: "product",
    title: {
      zh: "真实静态口播案例",
      en: "Real Static Talking Video",
    },
    description: {
      zh: "使用当前 Studio 静态口播链路生成：AI 文案、TTS 配音、头像视频和 MP4 下载。",
      en: "Generated by the current Studio static flow: AI script, TTS voiceover, avatar video, and MP4 download.",
    },
    thumbnailUrl: "/avatars/business_female_01.png",
    videoUrl: "https://povfvhdnrpytxbbyndit.supabase.co/storage/v1/object/public/videos/debug/static-avatar/f1597a62bfed4601a83d49eff7db2ebc.mp4?",
    taskId: "static-avatar-f1597a62bfed4601a83d49eff7db2ebc",
    duration: "45.000s",
    language: "zh",
    featured: true,
  },
  {
    id: "ecommerce-short-video",
    category: "commerce",
    title: {
      zh: "电商带货短视频",
      en: "E-commerce Short Video",
    },
    description: {
      zh: "为商品详情页、直播预热视频和投流素材快速生成真人感口播内容。",
      en: "Create human-feeling product narration for PDPs, livestream previews, and performance creatives.",
    },
    thumbnailUrl: "/avatars/business_male_01.png",
    videoUrl: "https://povfvhdnrpytxbbyndit.supabase.co/storage/v1/object/public/videos/avatar-results/56b1468c-f7a4-4cba-bab4-aaaa706a6ee8/e4385c1df5af4906a441828a1fe11126.mp4?",
    taskId: "56b1468c-f7a4-4cba-bab4-aaaa706a6ee8",
    duration: "15.552s",
    language: "multi",
  },
  {
    id: "business-training",
    category: "business",
    title: {
      zh: "企业培训说明",
      en: "Business Training",
    },
    description: {
      zh: "将业务汇报、流程说明和培训脚本转成统一风格的视频资产。",
      en: "Turn reports, process explainers, and training scripts into consistent video assets.",
    },
    thumbnailUrl: "/logo-transparent.png",
    videoUrl: "https://povfvhdnrpytxbbyndit.supabase.co/storage/v1/object/public/videos/avatar-results/e81a5831-6ff2-49b4-9e73-23742138b7ef/76cc7d699bac46cfb32f5da615919240.mp4?",
    taskId: "e81a5831-6ff2-49b4-9e73-23742138b7ef",
    duration: "15.216s",
    language: "multi",
  },
];

export function getFeaturedCases() {
  return customerCases.filter((item) => item.featured).slice(0, 2);
}
