from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

import httpx
from fastapi import HTTPException
from PIL import Image, ImageDraw, ImageFont
from supabase import Client

from app.core.config import settings
from app.services.storage import upload_public_bytes


async def render_product_video(
    supabase: Client,
    *,
    product_name: str,
    image_url: str,
    audio_url: str,
    subtitle_text: str,
    watermark: bool,
    max_seconds: int,
) -> str:
    async with httpx.AsyncClient(timeout=60) as client:
        image_bytes = (await client.get(image_url)).content
        audio_bytes = (await client.get(audio_url)).content

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        bg_path = tmp_path / "bg.png"
        audio_path = tmp_path / "voice.mp3"
        subtitle_path = tmp_path / "subtitles.srt"
        output_path = tmp_path / "final.mp4"

        _build_background(image_bytes, bg_path, product_name, watermark)
        audio_path.write_bytes(audio_bytes)
        subtitle_path.write_text(_build_srt(subtitle_text, max_seconds), encoding="utf-8")

        cmd = [
            settings.ffmpeg_path,
            "-y",
            "-loop",
            "1",
            "-i",
            str(bg_path),
            "-i",
            str(audio_path),
            "-t",
            str(max_seconds),
            "-vf",
            f"subtitles={_ffmpeg_path(subtitle_path)}:force_style='Fontsize=18,PrimaryColour=&HFFFFFF,OutlineColour=&H000000,BorderStyle=1,Outline=2,Alignment=2,MarginV=85'",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
            str(output_path),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            raise HTTPException(status_code=500, detail=f"FFmpeg render failed: {result.stderr[-1000:]}")

        video_bytes = output_path.read_bytes()

    return upload_public_bytes(
        supabase,
        settings.supabase_video_bucket,
        video_bytes,
        "generated",
        ".mp4",
        "video/mp4",
    )


def _build_background(image_bytes: bytes, output_path: Path, product_name: str, watermark: bool) -> None:
    canvas = Image.new("RGB", (720, 1280), "#07111f")
    draw = ImageDraw.Draw(canvas)
    for y in range(1280):
        color = (7, 17 + int(y / 1280 * 20), 31 + int(y / 1280 * 45))
        draw.line([(0, y), (720, y)], fill=color)

    with tempfile.NamedTemporaryFile(suffix=".img", delete=False) as file:
        file.write(image_bytes)
        image_path = Path(file.name)
    try:
        product = Image.open(image_path).convert("RGBA")
    finally:
        image_path.unlink(missing_ok=True)
    product.thumbnail((620, 620))
    x = (720 - product.width) // 2
    y = 230
    canvas.paste(product, (x, y), product)

    font_big = _font(44)
    font_small = _font(24)
    draw.text((48, 82), product_name[:16], fill="white", font=font_big)
    draw.text((48, 150), "AI 带货视频", fill="#22d3ee", font=font_small)
    draw.rounded_rectangle((48, 930, 672, 1060), radius=20, outline="#22d3ee", width=2)
    draw.text((76, 970), "看完再决定买不买", fill="white", font=_font(34))
    if watermark:
        draw.text((208, 1208), "Generated by kaiqiang.ai", fill="#dbeafe", font=_font(24))
    canvas.save(output_path)


def _font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        "C:/Windows/Fonts/msyh.ttc",
        "C:/Windows/Fonts/simhei.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def _build_srt(text: str, max_seconds: int) -> str:
    clean = " ".join(text.replace("\n", " ").split())
    chunks = [clean[i : i + 24] for i in range(0, len(clean), 24)] or [clean]
    per = max(2, max_seconds // max(len(chunks), 1))
    lines = []
    start = 0
    for index, chunk in enumerate(chunks[: max_seconds // 2], start=1):
        end = min(max_seconds, start + per)
        lines.append(f"{index}\n{_ts(start)} --> {_ts(end)}\n{chunk}\n")
        start = end
        if start >= max_seconds:
            break
    return "\n".join(lines)


def _ts(seconds: int) -> str:
    return f"00:00:{seconds:02d},000"


def _ffmpeg_path(path: Path) -> str:
    value = path.as_posix().replace(":", "\\:").replace("'", "\\'")
    return f"'{value}'"
